version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret